dashboard:
  refresh_interval: 1
  title: TrueNAS Dashboard
widgets:
  cpu:
    enabled: true
    show_cores: false
    show_temperature: true
  disks:
    devices:
    - all
    enabled: true
    show_io: true
    show_temperature: true
  memory:
    enabled: true
    show_arc: true
  network:
    enabled: true
    interfaces:
    - all
  pools:
    enabled: true
  vms:
    enabled: false
